In [2]:
import pandas as pd         
import numpy as np         

# Data Preparation

In [150]:
bridger_case=pd.read_excel('/Users/zouwenyuan/Desktop/ABCNY-PY/GWU_Final Bridger Scores.xlsx')
bridger_case

index      UID             Theme                 Category  \
0         0    UID-3  Positive Control              Exact Match   
1         1    UID-3  Positive Control              Exact Match   
2         2    UID-3  Positive Control              Exact Match   
3         3    UID-3  Positive Control              Exact Match   
4         4    UID-3  Positive Control              Exact Match   
...     ...      ...               ...                      ...   
4622   4622  UID-541    Name Additions  Name Part in the Middle   
4623   4623  UID-541    Name Additions  Name Part in the Middle   
4624   4624  UID-541    Name Additions  Name Part in the Middle   
4625   4625  UID-541    Name Additions  Name Part in the Middle   
4626   4626  UID-541    Name Additions  Name Part in the Middle   

            Sub-category Entity-Type    Test Case ID OFAC List UID  \
0       100% true match       Entity     UID-3 - 217          6936   
1       100% true match       Entity    UID-3 - 6782         26214   
2       100% true match       Entity    UID-3 - 5237         22284   
3       100% true match       Entity    UID-3 - 2858         15188   
4       100% true match       Entity    UID-3 - 7239         27233   
...                  ...         ...             ...           ...   
4622  2 name parts added      Vessel  UID-541 - 4411         19589   
4623  2 name parts added      Vessel  UID-541 - 5475         23162   
4624  2 name parts added      Vessel  UID-541 - 5476         23163   
4625  2 name parts added      Vessel  UID-541 - 5787         23733   
4626  2 name parts added      Vessel  UID-541 - 6250         25314   

                   Original Name                     Test Case Name  \
0     JAM'YAH TA'AWUN AL-ISLAMIA         JAM'YAH TA'AWUN AL-ISLAMIA   
1     GLOBOVISION TELE CA, CORP.         GLOBOVISION TELE CA, CORP.   
2           KOREAN PEOPLE'S ARMY               KOREAN PEOPLE'S ARMY   
3            RANCHO LA HERRADURA                RANCHO LA HERRADURA   
4            TECHNO ENERGY, S.A.                TECHNO ENERGY, S.A.   
...                          ...                                ...   
4622                 CHONG RIM 2       CHONG RIM priority cushion 2   
4623                  KUM SONG 7  KUM reservists transmittal SONG 7   
4624                KUM UN SAN 3        KUM seesaw UN SAN buckles 3   
4625                  SAM JONG 1       SAM energizer comment JONG 1   
4626                SHAHR E KORD          SHAHR mills master E KORD   

     BRIDGER SCORE  
0              100  
1              100  
2              100  
3              100  
4              100  
...            ...  
4622            82  
4623            82  
4624            78  
4625            82  
4626            82  

[4627 rows x 11 columns]

In [151]:
test_case=pd.read_csv('/Users/zouwenyuan/Desktop/final_test_cases.csv')
test_case

Unnamed: 0      UID             Theme                 Category  \
0              0    UID-3  Positive Control              Exact Match   
1              1    UID-3  Positive Control              Exact Match   
2              2    UID-3  Positive Control              Exact Match   
3              3    UID-3  Positive Control              Exact Match   
4              4    UID-3  Positive Control              Exact Match   
...          ...      ...               ...                      ...   
4622         814  UID-541    Name Additions  Name Part in the Middle   
4623         815  UID-541    Name Additions  Name Part in the Middle   
4624         816  UID-541    Name Additions  Name Part in the Middle   
4625         817  UID-541    Name Additions  Name Part in the Middle   
4626         818  UID-541    Name Additions  Name Part in the Middle   

            Sub-category Entity-Type    Test Case ID OFAC List UID  \
0       100% true match       Entity     UID-3 - 217          6936   
1       100% true match       Entity    UID-3 - 6782         26214   
2       100% true match       Entity    UID-3 - 5237         22284   
3       100% true match       Entity    UID-3 - 2858         15188   
4       100% true match       Entity    UID-3 - 7239         27233   
...                  ...         ...             ...           ...   
4622  2 name parts added      Vessel  UID-541 - 4411         19589   
4623  2 name parts added      Vessel  UID-541 - 5475         23162   
4624  2 name parts added      Vessel  UID-541 - 5476         23163   
4625  2 name parts added      Vessel  UID-541 - 5787         23733   
4626  2 name parts added      Vessel  UID-541 - 6250         25314   

                   Original Name                     Test Case Name  
0     JAM'YAH TA'AWUN AL-ISLAMIA         JAM'YAH TA'AWUN AL-ISLAMIA  
1     GLOBOVISION TELE CA, CORP.         GLOBOVISION TELE CA, CORP.  
2           KOREAN PEOPLE'S ARMY               KOREAN PEOPLE'S ARMY  
3            RANCHO LA HERRADURA                RANCHO LA HERRADURA  
4            TECHNO ENERGY, S.A.                TECHNO ENERGY, S.A.  
...                          ...                                ...  
4622                 CHONG RIM 2       CHONG RIM priority cushion 2  
4623                  KUM SONG 7  KUM reservists transmittal SONG 7  
4624                KUM UN SAN 3        KUM seesaw UN SAN buckles 3  
4625                  SAM JONG 1       SAM energizer comment JONG 1  
4626                SHAHR E KORD          SHAHR mills master E KORD  

[4627 rows x 10 columns]

In [152]:
new_score=bridger_case.merge(test_case, how='inner', on='Test Case ID')
new_score

index    UID_x           Theme_x               Category_x  \
0         0    UID-3  Positive Control              Exact Match   
1         1    UID-3  Positive Control              Exact Match   
2         2    UID-3  Positive Control              Exact Match   
3         3    UID-3  Positive Control              Exact Match   
4         4    UID-3  Positive Control              Exact Match   
...     ...      ...               ...                      ...   
4624   4622  UID-541    Name Additions  Name Part in the Middle   
4625   4623  UID-541    Name Additions  Name Part in the Middle   
4626   4624  UID-541    Name Additions  Name Part in the Middle   
4627   4625  UID-541    Name Additions  Name Part in the Middle   
4628   4626  UID-541    Name Additions  Name Part in the Middle   

          Sub-category_x Entity-Type_x    Test Case ID OFAC List UID_x  \
0       100% true match         Entity     UID-3 - 217            6936   
1       100% true match         Entity    UID-3 - 6782           26214   
2       100% true match         Entity    UID-3 - 5237           22284   
3       100% true match         Entity    UID-3 - 2858           15188   
4       100% true match         Entity    UID-3 - 7239           27233   
...                  ...           ...             ...             ...   
4624  2 name parts added        Vessel  UID-541 - 4411           19589   
4625  2 name parts added        Vessel  UID-541 - 5475           23162   
4626  2 name parts added        Vessel  UID-541 - 5476           23163   
4627  2 name parts added        Vessel  UID-541 - 5787           23733   
4628  2 name parts added        Vessel  UID-541 - 6250           25314   

                 Original Name_x                   Test Case Name_x  \
0     JAM'YAH TA'AWUN AL-ISLAMIA         JAM'YAH TA'AWUN AL-ISLAMIA   
1     GLOBOVISION TELE CA, CORP.         GLOBOVISION TELE CA, CORP.   
2           KOREAN PEOPLE'S ARMY               KOREAN PEOPLE'S ARMY   
3            RANCHO LA HERRADURA                RANCHO LA HERRADURA   
4            TECHNO ENERGY, S.A.                TECHNO ENERGY, S.A.   
...                          ...                                ...   
4624                 CHONG RIM 2       CHONG RIM priority cushion 2   
4625                  KUM SONG 7  KUM reservists transmittal SONG 7   
4626                KUM UN SAN 3        KUM seesaw UN SAN buckles 3   
4627                  SAM JONG 1       SAM energizer comment JONG 1   
4628                SHAHR E KORD          SHAHR mills master E KORD   

     BRIDGER SCORE  Unnamed: 0    UID_y           Theme_y  \
0              100           0    UID-3  Positive Control   
1              100           1    UID-3  Positive Control   
2              100           2    UID-3  Positive Control   
3              100           3    UID-3  Positive Control   
4              100           4    UID-3  Positive Control   
...            ...         ...      ...               ...   
4624            82         814  UID-541    Name Additions   
4625            82         815  UID-541    Name Additions   
4626            78         816  UID-541    Name Additions   
4627            82         817  UID-541    Name Additions   
4628            82         818  UID-541    Name Additions   

                   Category_y      Sub-category_y Entity-Type_y  \
0                 Exact Match    100% true match         Entity   
1                 Exact Match    100% true match         Entity   
2                 Exact Match    100% true match         Entity   
3                 Exact Match    100% true match         Entity   
4                 Exact Match    100% true match         Entity   
...                       ...                 ...           ...   
4624  Name Part in the Middle  2 name parts added        Vessel   
4625  Name Part in the Middle  2 name parts added        Vessel   
4626  Name Part in the Middle  2 name parts added        Vessel   
4627  Name Part in the Middle  2 name parts added       

In [153]:
new_score.columns

Index(['index', 'UID_x', 'Theme_x', 'Category_x', 'Sub-category_x',
       'Entity-Type_x', 'Test Case ID', 'OFAC List UID_x', 'Original Name_x',
       'Test Case Name_x', 'BRIDGER SCORE', 'Unnamed: 0', 'UID_y', 'Theme_y',
       'Category_y', 'Sub-category_y', 'Entity-Type_y', 'OFAC List UID_y',
       'Original Name_y', 'Test Case Name_y'],
      dtype='object')

In [154]:
clean_score_case=new_score.drop(columns=['index', 'UID_x', 'Theme_x', 'Category_x', 'Sub-category_x',
       'Entity-Type_x', 'OFAC List UID_x', 'Unnamed: 0', 'UID_y', 'Theme_y',
       'Category_y', 'Sub-category_y', 'Entity-Type_y', 'OFAC List UID_y',
       'Original Name_y', 'Test Case Name_y'])
clean_score_case

Test Case ID             Original Name_x  \
0        UID-3 - 217  JAM'YAH TA'AWUN AL-ISLAMIA   
1       UID-3 - 6782  GLOBOVISION TELE CA, CORP.   
2       UID-3 - 5237        KOREAN PEOPLE'S ARMY   
3       UID-3 - 2858         RANCHO LA HERRADURA   
4       UID-3 - 7239         TECHNO ENERGY, S.A.   
...              ...                         ...   
4624  UID-541 - 4411                 CHONG RIM 2   
4625  UID-541 - 5475                  KUM SONG 7   
4626  UID-541 - 5476                KUM UN SAN 3   
4627  UID-541 - 5787                  SAM JONG 1   
4628  UID-541 - 6250                SHAHR E KORD   

                       Test Case Name_x BRIDGER SCORE  
0            JAM'YAH TA'AWUN AL-ISLAMIA           100  
1            GLOBOVISION TELE CA, CORP.           100  
2                  KOREAN PEOPLE'S ARMY           100  
3                   RANCHO LA HERRADURA           100  
4                   TECHNO ENERGY, S.A.           100  
...                                 ...           ...  
4624       CHONG RIM priority cushion 2            82  
4625  KUM reservists transmittal SONG 7            82  
4626        KUM seesaw UN SAN buckles 3            78  
4627       SAM energizer comment JONG 1            82  
4628          SHAHR mills master E KORD            82  

[4629 rows x 4 columns]

In [155]:
clean_score_case['predict']=''
clean_score_case

Test Case ID             Original Name_x  \
0        UID-3 - 217  JAM'YAH TA'AWUN AL-ISLAMIA   
1       UID-3 - 6782  GLOBOVISION TELE CA, CORP.   
2       UID-3 - 5237        KOREAN PEOPLE'S ARMY   
3       UID-3 - 2858         RANCHO LA HERRADURA   
4       UID-3 - 7239         TECHNO ENERGY, S.A.   
...              ...                         ...   
4624  UID-541 - 4411                 CHONG RIM 2   
4625  UID-541 - 5475                  KUM SONG 7   
4626  UID-541 - 5476                KUM UN SAN 3   
4627  UID-541 - 5787                  SAM JONG 1   
4628  UID-541 - 6250                SHAHR E KORD   

                       Test Case Name_x BRIDGER SCORE predict  
0            JAM'YAH TA'AWUN AL-ISLAMIA           100          
1            GLOBOVISION TELE CA, CORP.           100          
2                  KOREAN PEOPLE'S ARMY           100          
3                   RANCHO LA HERRADURA           100          
4                   TECHNO ENERGY, S.A.           100          
...                                 ...           ...     ...  
4624       CHONG RIM priority cushion 2            82          
4625  KUM reservists transmittal SONG 7            82          
4626        KUM seesaw UN SAN buckles 3            78          
4627       SAM energizer comment JONG 1            82          
4628          SHAHR mills master E KORD            82          

[4629 rows x 5 columns]

In [156]:
clean_score_case[clean_score_case['Original Name_x'].isnull()].index.tolist()

[]

In [157]:
clean_score_case.to_csv('/Users/zouwenyuan/Desktop/ABCNY-PY/clean_score_case.csv')

In [10]:
for i in range(len(clean_score_case)):
    if clean_score_case.at[i,'BRIDGER SCORE']=='NO MATCH':
        clean_score_case.at[i,'predict']=0
    else:
        clean_score_case.at[i,'predict']=1
clean_score_case

Test Case ID             Original Name_x  \
0        UID-3 - 217  JAM'YAH TA'AWUN AL-ISLAMIA   
1       UID-3 - 6782  GLOBOVISION TELE CA, CORP.   
2       UID-3 - 5237        KOREAN PEOPLE'S ARMY   
3       UID-3 - 2858         RANCHO LA HERRADURA   
4       UID-3 - 7239         TECHNO ENERGY, S.A.   
...              ...                         ...   
4624  UID-541 - 4411                 CHONG RIM 2   
4625  UID-541 - 5475                  KUM SONG 7   
4626  UID-541 - 5476                KUM UN SAN 3   
4627  UID-541 - 5787                  SAM JONG 1   
4628  UID-541 - 6250                SHAHR E KORD   

                       Test Case Name_x BRIDGER SCORE predict  
0            JAM'YAH TA'AWUN AL-ISLAMIA           100       1  
1            GLOBOVISION TELE CA, CORP.           100       1  
2                  KOREAN PEOPLE'S ARMY           100       1  
3                   RANCHO LA HERRADURA           100       1  
4                   TECHNO ENERGY, S.A.           100       1  
...                                 ...           ...     ...  
4624       CHONG RIM priority cushion 2            82       1  
4625  KUM reservists transmittal SONG 7            82       1  
4626        KUM seesaw UN SAN buckles 3            78       1  
4627       SAM energizer comment JONG 1            82       1  
4628          SHAHR mills master E KORD            82       1  

[4629 rows x 5 columns]

In [11]:
df2 = clean_score_case.rename({'Original Name_x': 'Original Name', 'Test Case Name_x': 'Test Case Name'}, axis=1) 
fuzzy_score_test=df2.drop(columns=['BRIDGER SCORE'])
fuzzy_score_test

Test Case ID               Original Name  \
0        UID-3 - 217  JAM'YAH TA'AWUN AL-ISLAMIA   
1       UID-3 - 6782  GLOBOVISION TELE CA, CORP.   
2       UID-3 - 5237        KOREAN PEOPLE'S ARMY   
3       UID-3 - 2858         RANCHO LA HERRADURA   
4       UID-3 - 7239         TECHNO ENERGY, S.A.   
...              ...                         ...   
4624  UID-541 - 4411                 CHONG RIM 2   
4625  UID-541 - 5475                  KUM SONG 7   
4626  UID-541 - 5476                KUM UN SAN 3   
4627  UID-541 - 5787                  SAM JONG 1   
4628  UID-541 - 6250                SHAHR E KORD   

                         Test Case Name predict  
0            JAM'YAH TA'AWUN AL-ISLAMIA       1  
1            GLOBOVISION TELE CA, CORP.       1  
2                  KOREAN PEOPLE'S ARMY       1  
3                   RANCHO LA HERRADURA       1  
4                   TECHNO ENERGY, S.A.       1  
...                                 ...     ...  
4624       CHONG RIM priority cushion 2       1  
4625  KUM reservists transmittal SONG 7       1  
4626        KUM seesaw UN SAN buckles 3       1  
4627       SAM energizer comment JONG 1       1  
4628          SHAHR mills master E KORD       1  

[4629 rows x 4 columns]

In [12]:
false_match_case=pd.read_csv('/Users/zouwenyuan/Desktop/ABCNY-PY/false_match_cases.csv')
false_match_case['predict']=0
false_score_test=false_match_case.drop(columns=['UID', 'Theme', 'Category', 'Sub-category', 'Entity-Type', 
                                                 'OFAC List UID'])
false_score_test

Test Case ID                                      Original Name  \
0      No Match - 7516  CONSORCIO VENEZOLANO DE INDUSTRIAS AERONAUTICA...   
1      No Match - 6090                                  HASSAN, Hameed ul   
2      No Match - 4524                        GALLON ARISTIZABAL, Mariana   
3      No Match - 7344                                        ESSA, Salim   
4      No Match - 9846                                  TIPOGRAFIYA IRKUT   
...                ...                                                ...   
9247   No Match - 1578                     AGUIRRE SANCHEZ, Blanca Armida   
9248   No Match - 9870                        BORIS, Albert Alexandrovich   
9249   No Match - 6664                                  GHADIR KANI ARIYA   
9250  No Match - 10922                   SWANSEAS PORT SERVICES PTE. LTD.   
9251   No Match - 4019  RUSSIAN AGENCY FOR EXPORT CREDIT AND INVESTMEN...   

                                   Test Case Name  predict  
0                     BASOVA, Lidia Aleksandrovna        0  
1                        THAINGUI S.A.L. OFFSHORE        0  
2                           200G PSA HOLDINGS LLC        0  
3                   CARRENO ESCOBAR, Pedro Miguel        0  
4                                   P.B. SADR CO.        0  
...                                           ...      ...  
9247                COMERCIAL DOMELY, S.A. DE C.V        0  
9248                       HOSSEINI, Mohammad Ali        0  
9249                  NETYKSHO, Viktor Borisovich        0  
9250                               HAWRANI, Habib        0  
9251  OPEN JOINT STOCK COMPANY 'KONTSERN IZHMASH'        0  

[9252 rows x 4 columns]

In [13]:
exact_match_case=pd.read_csv('/Users/zouwenyuan/Desktop/ABCNY-PY/exact_match_cases.csv')
exact_match_case['predict']=1
exact_score_test=exact_match_case.drop(columns=['UID', 'Theme', 'Category', 'Sub-category', 'Entity-Type', 
                                                 'OFAC List UID'])
exact_score_test

Test Case ID                      Original Name  \
0      Exact Match - 103          NASSER DAVID, Julio Cesar   
1     Exact Match - 1192    RESTREPO VICTORIA, Maria Teresa   
2     Exact Match - 3229           PARS AMAYESH SANAAT KISH   
3     Exact Match - 7022               VISMURADOV, Abuzayed   
4     Exact Match - 9883               JESTAR SANAT DELIJAN   
...                  ...                                ...   
4621  Exact Match - 4796                          AL-QASIUN   
4622  Exact Match - 2726  GONZALEZ PARADA, Juvencio Ignacio   
4623  Exact Match - 9959                IMENIE TSARGRAD OOO   
4624  Exact Match - 3549                      KOZAK, Dmitry   
4625  Exact Match - 8193                    IMIRBAKI, Arken   

                         Test Case Name  predict  
0             NASSER DAVID, Julio Cesar        1  
1       RESTREPO VICTORIA, Maria Teresa        1  
2              PARS AMAYESH SANAAT KISH        1  
3                  VISMURADOV, Abuzayed        1  
4                  JESTAR SANAT DELIJAN        1  
...                                 ...      ...  
4621                          AL-QASIUN        1  
4622  GONZALEZ PARADA, Juvencio Ignacio        1  
4623                IMENIE TSARGRAD OOO        1  
4624                      KOZAK, Dmitry        1  
4625                    IMIRBAKI, Arken        1  

[4626 rows x 4 columns]

In [14]:
df2 = fuzzy_score_test.append(false_score_test, ignore_index=True)
all_data = df2.append(exact_score_test, ignore_index=True)
all_data

Test Case ID                      Original Name  \
0             UID-3 - 217         JAM'YAH TA'AWUN AL-ISLAMIA   
1            UID-3 - 6782         GLOBOVISION TELE CA, CORP.   
2            UID-3 - 5237               KOREAN PEOPLE'S ARMY   
3            UID-3 - 2858                RANCHO LA HERRADURA   
4            UID-3 - 7239                TECHNO ENERGY, S.A.   
...                   ...                                ...   
18502  Exact Match - 4796                          AL-QASIUN   
18503  Exact Match - 2726  GONZALEZ PARADA, Juvencio Ignacio   
18504  Exact Match - 9959                IMENIE TSARGRAD OOO   
18505  Exact Match - 3549                      KOZAK, Dmitry   
18506  Exact Match - 8193                    IMIRBAKI, Arken   

                          Test Case Name predict  
0             JAM'YAH TA'AWUN AL-ISLAMIA       1  
1             GLOBOVISION TELE CA, CORP.       1  
2                   KOREAN PEOPLE'S ARMY       1  
3                    RANCHO LA HERRADURA       1  
4                    TECHNO ENERGY, S.A.       1  
...                                  ...     ...  
18502                          AL-QASIUN       1  
18503  GONZALEZ PARADA, Juvencio Ignacio       1  
18504                IMENIE TSARGRAD OOO       1  
18505                      KOZAK, Dmitry       1  
18506                    IMIRBAKI, Arken       1  

[18507 rows x 4 columns]

In [15]:
all_data[all_data['Original Name'].isnull()].index.tolist()

[8664, 18407]

In [16]:
all_data.drop([8661,18404], axis=0, inplace=True)
all_data.reset_index(drop=True)

Test Case ID                      Original Name  \
0             UID-3 - 217         JAM'YAH TA'AWUN AL-ISLAMIA   
1            UID-3 - 6782         GLOBOVISION TELE CA, CORP.   
2            UID-3 - 5237               KOREAN PEOPLE'S ARMY   
3            UID-3 - 2858                RANCHO LA HERRADURA   
4            UID-3 - 7239                TECHNO ENERGY, S.A.   
...                   ...                                ...   
18500  Exact Match - 4796                          AL-QASIUN   
18501  Exact Match - 2726  GONZALEZ PARADA, Juvencio Ignacio   
18502  Exact Match - 9959                IMENIE TSARGRAD OOO   
18503  Exact Match - 3549                      KOZAK, Dmitry   
18504  Exact Match - 8193                    IMIRBAKI, Arken   

                          Test Case Name predict  
0             JAM'YAH TA'AWUN AL-ISLAMIA       1  
1             GLOBOVISION TELE CA, CORP.       1  
2                   KOREAN PEOPLE'S ARMY       1  
3                    RANCHO LA HERRADURA       1  
4                    TECHNO ENERGY, S.A.       1  
...                                  ...     ...  
18500                          AL-QASIUN       1  
18501  GONZALEZ PARADA, Juvencio Ignacio       1  
18502                IMENIE TSARGRAD OOO       1  
18503                      KOZAK, Dmitry       1  
18504                    IMIRBAKI, Arken       1  

[18505 rows x 4 columns]

In [17]:
all_data.to_csv('/Users/zouwenyuan/Desktop/predictions.csv', index = False)

In [18]:
score_test=pd.read_csv('/Users/zouwenyuan/Desktop/predictions.csv')
score_test

Test Case ID                      Original Name  \
0             UID-3 - 217         JAM'YAH TA'AWUN AL-ISLAMIA   
1            UID-3 - 6782         GLOBOVISION TELE CA, CORP.   
2            UID-3 - 5237               KOREAN PEOPLE'S ARMY   
3            UID-3 - 2858                RANCHO LA HERRADURA   
4            UID-3 - 7239                TECHNO ENERGY, S.A.   
...                   ...                                ...   
18500  Exact Match - 4796                          AL-QASIUN   
18501  Exact Match - 2726  GONZALEZ PARADA, Juvencio Ignacio   
18502  Exact Match - 9959                IMENIE TSARGRAD OOO   
18503  Exact Match - 3549                      KOZAK, Dmitry   
18504  Exact Match - 8193                    IMIRBAKI, Arken   

                          Test Case Name  predict  
0             JAM'YAH TA'AWUN AL-ISLAMIA        1  
1             GLOBOVISION TELE CA, CORP.        1  
2                   KOREAN PEOPLE'S ARMY        1  
3                    RANCHO LA HERRADURA        1  
4                    TECHNO ENERGY, S.A.        1  
...                                  ...      ...  
18500                          AL-QASIUN        1  
18501  GONZALEZ PARADA, Juvencio Ignacio        1  
18502                IMENIE TSARGRAD OOO        1  
18503                      KOZAK, Dmitry        1  
18504                    IMIRBAKI, Arken        1  

[18505 rows x 4 columns]

In [35]:
new_test_case=pd.read_csv('/Users/zouwenyuan/Desktop/similarity_metrics_new.csv')
new_test_case

Original Name                     Test Case Name  \
0             JAM'YAH TA'AWUN AL-ISLAMIA         JAM'YAH TA'AWUN AL-ISLAMIA   
1             GLOBOVISION TELE CA, CORP.         GLOBOVISION TELE CA, CORP.   
2                   KOREAN PEOPLE'S ARMY               KOREAN PEOPLE'S ARMY   
3                    RANCHO LA HERRADURA                RANCHO LA HERRADURA   
4                    TECHNO ENERGY, S.A.                TECHNO ENERGY, S.A.   
...                                  ...                                ...   
18497                          AL-QASIUN                          AL-QASIUN   
18498  GONZALEZ PARADA, Juvencio Ignacio  GONZALEZ PARADA, Juvencio Ignacio   
18499                IMENIE TSARGRAD OOO                IMENIE TSARGRAD OOO   
18500                      KOZAK, Dmitry                      KOZAK, Dmitry   
18501                    IMIRBAKI, Arken                    IMIRBAKI, Arken   

             Test Case ID   Match Type  Fuzzy Ratio  Hamming Score  \
0             UID-3 - 217  Fuzzy Match          100            0.0   
1            UID-3 - 6782  Fuzzy Match          100            0.0   
2            UID-3 - 5237  Fuzzy Match          100            0.0   
3            UID-3 - 2858  Fuzzy Match          100            0.0   
4            UID-3 - 7239  Fuzzy Match          100            0.0   
...                   ...          ...          ...            ...   
18497  Exact Match - 4796  Exact Match          100            NaN   
18498  Exact Match - 2726  Exact Match          100            NaN   
18499  Exact Match - 9959  Exact Match          100            NaN   
18500  Exact Match - 3549  Exact Match          100            NaN   
18501  Exact Match - 8193  Exact Match          100            NaN   

       Cosine Similarity  Double Metaphone Score  Jaro-Winkler Score  \
0                    1.0                     100                 1.0   
1                    1.0                     100                 1.0   
2                    1.0                     100                 1.0   
3                    1.0                     100                 1.0   
4                    1.0                     100                 1.0   
...                  ...                     ...                 ...   
18497                1.0                     100                 1.0   
18498                1.0                     100                 1.0   
18499                1.0                     100                 1.0   
18500                1.0                     100                 1.0   
18501                1.0                     100                 1.0   

       Levenshtein Distance Score  
0                               0  
1                               0  
2                               0  
3                               0  
4                               0  
...                           ...  
18497                           0  
18498                           0  
18499                           0  
18500                           0  
18501                           0  

[18502 rows x 10 columns]

In [39]:
final_test_case=new_test_case.merge(score_test, on='Test Case ID')
final_test_case.columns

Index(['Original Name_x', 'Test Case Name_x', 'Test Case ID', 'Match Type',
       'Fuzzy Ratio', 'Hamming Score', 'Cosine Similarity',
       'Double Metaphone Score', 'Jaro-Winkler Score',
       'Levenshtein Distance Score', 'Original Name_y', 'Test Case Name_y',
       'predict'],
      dtype='object')

In [40]:
final_case=final_test_case.drop(columns=['Original Name_x', 'Test Case Name_x', 'Test Case ID', 'Match Type',
       'Hamming Score', 'Original Name_y', 'Test Case Name_y'])
final_case

Fuzzy Ratio  Cosine Similarity  Double Metaphone Score  \
0              100                1.0                     100   
1              100                1.0                     100   
2              100                1.0                     100   
3              100                1.0                     100   
4              100                1.0                     100   
...            ...                ...                     ...   
18501          100                1.0                     100   
18502          100                1.0                     100   
18503          100                1.0                     100   
18504          100                1.0                     100   
18505          100                1.0                     100   

       Jaro-Winkler Score  Levenshtein Distance Score  predict  
0                     1.0                           0        1  
1                     1.0                           0        1  
2                     1.0                           0        1  
3                     1.0                           0        1  
4                     1.0                           0        1  
...                   ...                         ...      ...  
18501                 1.0                           0        1  
18502                 1.0                           0        1  
18503                 1.0                           0        1  
18504                 1.0                           0        1  
18505                 1.0                           0        1  

[18506 rows x 6 columns]

In [42]:
final_case[final_case['predict'].isnull()].index.tolist()

[]

In [44]:
final_case.to_csv('/Users/zouwenyuan/Desktop/test_for_classification.csv', index = False)

# Binary Classification

In [45]:
from sklearn.model_selection import train_test_split


In [106]:
X=final_case[['Fuzzy Ratio', 'Cosine Similarity', 'Double Metaphone Score',
              'Jaro-Winkler Score', 'Levenshtein Distance Score']]

In [101]:
Y=final_case['predict']

In [102]:
from sklearn.preprocessing import StandardScaler
 
scale= StandardScaler()
 
# standardization of dependent variables
scaled_data = scale.fit_transform(X) 
print(scaled_data)

[[ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 ...
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]]


In [103]:
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, test_size=0.3,random_state=42) # 70% training and 30% test

## SVM

In [107]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
# define dataset
# define model and parameters
model = SVC()
kernel = ['poly', 'rbf', 'sigmoid']
C = [50, 10, 1.0, 0.1, 0.01]
gamma = ['scale']
# define grid search
grid = dict(kernel=kernel,C=C,gamma=gamma)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(scaled_data, Y)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.966137 using {'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}
0.957419 (0.005260) with: {'C': 50, 'gamma': 'scale', 'kernel': 'poly'}
0.966137 (0.004068) with: {'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}
0.905220 (0.006511) with: {'C': 50, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.954177 (0.005820) with: {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}
0.965182 (0.003895) with: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
0.905256 (0.006487) with: {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.953330 (0.005558) with: {'C': 1.0, 'gamma': 'scale', 'kernel': 'poly'}
0.963453 (0.004301) with: {'C': 1.0, 'gamma': 'scale', 'kernel': 'rbf'}
0.905742 (0.006665) with: {'C': 1.0, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.955492 (0.005157) with: {'C': 0.1, 'gamma': 'scale', 'kernel': 'poly'}
0.960805 (0.004713) with: {'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}
0.911218 (0.006764) with: {'C': 0.1, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.917216 (0.007474) with: {'C': 0.01, 'gamma': 'scale', 

In [108]:
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
# define dataset
# define model and parameters
model = SVC()
kernel = ['poly', 'rbf', 'sigmoid']
C = [50, 10, 1.0, 0.1, 0.01]
gamma = ['scale']
# define grid search
grid = dict(kernel=kernel,C=C,gamma=gamma)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X, Y)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.959490 using {'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}
0.957653 (0.004768) with: {'C': 50, 'gamma': 'scale', 'kernel': 'poly'}
0.959490 (0.004969) with: {'C': 50, 'gamma': 'scale', 'kernel': 'rbf'}
0.304626 (0.306460) with: {'C': 50, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.951583 (0.005350) with: {'C': 10, 'gamma': 'scale', 'kernel': 'poly'}
0.947440 (0.006000) with: {'C': 10, 'gamma': 'scale', 'kernel': 'rbf'}
0.355801 (0.339402) with: {'C': 10, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.941010 (0.006267) with: {'C': 1.0, 'gamma': 'scale', 'kernel': 'poly'}
0.937389 (0.006283) with: {'C': 1.0, 'gamma': 'scale', 'kernel': 'rbf'}
0.278212 (0.286010) with: {'C': 1.0, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.934345 (0.006857) with: {'C': 0.1, 'gamma': 'scale', 'kernel': 'poly'}
0.931607 (0.005836) with: {'C': 0.1, 'gamma': 'scale', 'kernel': 'rbf'}
0.153193 (0.007554) with: {'C': 0.1, 'gamma': 'scale', 'kernel': 'sigmoid'}
0.926510 (0.005934) with: {'C': 0.01, 'gamma': 'scale', 

In [111]:
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, test_size=0.3,random_state=42) # 70% training and 30% test

In [116]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svc = SVC()
parameters = [
    {
        'C': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
        'gamma': [0.00001, 0.0001, 0.001, 0.1, 1, 10, 100, 1000],
        'kernel': ['rbf']
    },
    {
        'C': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19],
        'kernel': ['linear']
    }
]
clf = GridSearchCV(svc, parameters, cv=5, n_jobs=8)
clf.fit(X_train, y_train)
print(clf.best_params_)



{'C': 19, 'gamma': 1, 'kernel': 'rbf'}


In [143]:
best_model = clf.best_estimator_
y_pred=best_model.predict(X_test)
y_pred

array([1, 0, 0, ..., 1, 0, 1])

#Import svm model
from sklearn import svm

#Create a svm Classifier
clf = svm.SVC(kernel='linear') # Linear Kernel

#Train the model using the training sets
clf.fit(X_train, y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [144]:
svm_data = clf.predict(X).tolist()

In [145]:
len(svm_data)

18506

In [121]:
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

# Model Accuracy: how often is the classifier correct?
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9661383285302594


In [122]:
# Model Precision: what percentage of positive tuples are labeled as such?
print("Precision:",metrics.precision_score(y_test, y_pred))

# Model Recall: what percentage of positive tuples are labelled as such?
print("Recall:",metrics.recall_score(y_test, y_pred))

Precision: 0.9470198675496688
Recall: 0.9790575916230366


In [123]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[2933,  136],
       [  52, 2431]])

### With Gram

In [89]:
#from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [90]:
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, test_size=0.3,random_state=42) # 70% training and 30% test
clf = svm.SVC(kernel='precomputed')
gram_train = np.dot(X_train, X_train.T)
clf.fit(gram_train, y_train)
SVC(kernel='precomputed') 
gram_test = np.dot(X_test, X_train.T)
clf.predict(gram_test)

array([1, 0, 0, ..., 1, 0, 1])

In [91]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[2914,  155],
       [  75, 2408]])

## KNN

In [125]:
# example of grid searching key hyperparametres for KNeighborsClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
n_neighbors = [2,3]
weights = ['uniform', 'distance']
metric = ['euclidean', 'manhattan', 'minkowski']
# define grid search
grid = dict(n_neighbors=n_neighbors,weights=weights,metric=metric)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(scaled_data, Y)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.966137 using {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}
0.956284 (0.004716) with: {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'uniform'}
0.961940 (0.003591) with: {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'distance'}
0.965254 (0.003915) with: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'}
0.965020 (0.004148) with: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
0.957491 (0.005115) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'uniform'}
0.962426 (0.003822) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'distance'}
0.966065 (0.004408) with: {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'}
0.966137 (0.004043) with: {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}
0.956284 (0.004716) with: {'metric': 'minkowski', 'n_neighbors': 2, 'weights': 'uniform'}
0.961940 (0.003591) with: {'metric': 'minkowski', 'n_neighbors': 2, 'weights': 'distance'}
0.965254 

In [126]:
# example of grid searching key hyperparametres for KNeighborsClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
n_neighbors = [2,3]
weights = ['uniform', 'distance']
metric = ['euclidean', 'manhattan', 'minkowski']
# define grid search
grid = dict(n_neighbors=n_neighbors,weights=weights,metric=metric)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(X, Y)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.943586 using {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'}
0.928492 (0.005967) with: {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'uniform'}
0.934670 (0.006192) with: {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'distance'}
0.941532 (0.005157) with: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'}
0.940344 (0.004852) with: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
0.931590 (0.005545) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'uniform'}
0.936903 (0.005700) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'distance'}
0.943586 (0.004711) with: {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'}
0.943045 (0.004360) with: {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}
0.928492 (0.005967) with: {'metric': 'minkowski', 'n_neighbors': 2, 'weights': 'uniform'}
0.934670 (0.006192) with: {'metric': 'minkowski', 'n_neighbors': 2, 'weights': 'distance'}
0.941532 (

In [127]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
  

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, 
                                                    test_size=0.3,random_state=42) # 70% training and 30% test

  
knn = KNeighborsClassifier(n_neighbors=2)
best_method = ""
best_score = 0.0

for method in ["uniform", "distance"]:
    for k in range(2,3):
        knn_clf = KNeighborsClassifier(n_neighbors = k)
        knn_clf.fit(X_train, y_train)
        knn_score = knn_clf.score(X_test, y_test)
        if knn_score > best_score:
            best_score = knn_score
            best_k = k
            best_method = method

print("best_mrthod = ", best_method)
print("best_k = ", best_k)
print("best_score = ", best_score)

best_mrthod =  uniform
best_k =  2
best_score =  0.9553314121037464


In [128]:
best_p = -1
best_score = 0.0
best_k = -1
for k in range(2,3):
    for p in range(1, 6):
        knn_clf = KNeighborsClassifier(n_neighbors = k, weights = "distance", p = p)
        knn_clf.fit(X_train, y_train)
        knn_score = knn_clf.score(X_test, y_test)
        if knn_score > best_score:
            best_score = knn_score
            best_k = k
            best_p = p

print("best_p = ", best_p)
print("best_k = ", best_k)
print("best_score = ", best_score) 

best_p =  1
best_k =  2
best_score =  0.9592939481268011


In [130]:
#0.962426 (0.003822) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'distance'}
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
  

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, 
                                                    test_size=0.3,random_state=42) # 70% training and 30% test

  
knn = KNeighborsClassifier(n_neighbors=2, weights='uniform', algorithm='auto', leaf_size=30, p=1, metric='manhattan')
  
knn.fit(X_train, y_train)
  
# Predict on dataset which model has not seen before
print(knn.predict(X_test))

[0 0 0 ... 1 0 1]


In [131]:
KNN=knn.predict(X).tolist()

In [132]:
len(KNN)

18506

In [133]:
from sklearn.metrics import mean_squared_error
from math import sqrt
train_preds = knn.predict(X_train)
mse = mean_squared_error(y_train, train_preds)
rmse = sqrt(mse)
rmse

0.13611427506959425

In [134]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.9661383285302594


In [135]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
cm

array([[2933,  136],
       [  52, 2431]])

In [146]:
# Calculate the accuracy of the model
print(knn.score(X_test, y_test))

0.9535302593659942


In [147]:
final_case['SVM'] = svm_data
final_case['KNN'] = KNN
final_case

Fuzzy Ratio  Cosine Similarity  Double Metaphone Score  \
0              100                1.0                     100   
1              100                1.0                     100   
2              100                1.0                     100   
3              100                1.0                     100   
4              100                1.0                     100   
...            ...                ...                     ...   
18501          100                1.0                     100   
18502          100                1.0                     100   
18503          100                1.0                     100   
18504          100                1.0                     100   
18505          100                1.0                     100   

       Jaro-Winkler Score  Levenshtein Distance Score  predict  SVM  KNN  
0                     1.0                           0        1    1    1  
1                     1.0                           0        1    1    1  
2                     1.0                           0        1    1    1  
3                     1.0                           0        1    1    1  
4                     1.0                           0        1    1    1  
...                   ...                         ...      ...  ...  ...  
18501                 1.0                           0        1    1    1  
18502                 1.0                           0        1    1    1  
18503                 1.0                           0        1    1    1  
18504                 1.0                           0        1    1    1  
18505                 1.0                           0        1    1    1  

[18506 rows x 8 columns]

In [148]:
difference_svm=0
difference_knn=0

for i in range(len(final_case)):
    if final_case.at[i,'predict']!=final_case.at[i,'SVM']:
        difference_svm+=1
    if final_case.at[i,'predict']!=final_case.at[i,'KNN']:
        difference_knn+=1
print(difference_svm,difference_knn)

10060 1667


In [142]:
final_case.iloc[245]

Fuzzy Ratio                   62.000000
Cosine Similarity              0.449436
Double Metaphone Score        59.000000
Jaro-Winkler Score             0.471717
Levenshtein Distance Score    18.000000
predict                        0.000000
SVM                            1.000000
KNN                            0.000000
Name: 245, dtype: float64

## Logistic Regression?
-need more specific bridger score

# Multiple Classification
k-Nearest Neighbors.
Decision Trees.
Naive Bayes.
Random Forest.
Gradient Boosting.

In [158]:
multiple_case=pd.read_csv('/Users/zouwenyuan/Desktop/test_for_multiple-classification.csv')

In [159]:
X=multiple_case[['Fuzzy Ratio', 'Cosine Similarity', 'Double Metaphone Score',
              'Jaro-Winkler Score', 'Levenshtein Distance Score']]

In [160]:
Y=multiple_case['predict']

In [161]:
from sklearn.preprocessing import StandardScaler
 
scale= StandardScaler()
 
# standardization of dependent variables
scaled_data = scale.fit_transform(X) 
print(scaled_data)

[[ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 ...
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]
 [ 1.24442838  1.39469548  1.09420492  1.20074681 -1.03034383]]


In [162]:
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, test_size=0.3,random_state=42) # 70% training and 30% test

## KNN

In [172]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
  

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, 
                                                    test_size=0.3,random_state=42) # 70% training and 30% test

  
knn = KNeighborsClassifier(n_neighbors=2)
best_method = ""
best_score = 0.0
best_p = -1

for method in ["uniform", "distance"]:
    for p in range(1, 6):
        knn_clf = KNeighborsClassifier(n_neighbors = 3, weights = method, p = p)
        knn_clf.fit(X_train, y_train)
        knn_score = knn_clf.score(X_test, y_test)
        if knn_score > best_score:
            best_score = knn_score
            best_p = p

print("best_p = ", best_p)
print("best_method = ", best_method)
print("best_score = ", best_score) 

best_p =  2
best_method =  
best_score =  0.779178674351585


In [174]:
# example of grid searching key hyperparametres for KNeighborsClassifier
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()
n_neighbors = [2,3]
weights = ['uniform', 'distance']
metric = ['euclidean', 'manhattan', 'minkowski']
# define grid search
grid = dict(n_neighbors=n_neighbors,weights=weights,metric=metric)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(scaled_data, Y)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.953042 using {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}
0.929356 (0.043943) with: {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'uniform'}
0.935084 (0.044697) with: {'metric': 'euclidean', 'n_neighbors': 2, 'weights': 'distance'}
0.952105 (0.004570) with: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'uniform'}
0.952196 (0.004270) with: {'metric': 'euclidean', 'n_neighbors': 3, 'weights': 'distance'}
0.930527 (0.044590) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'uniform'}
0.935751 (0.044543) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'distance'}
0.952664 (0.004835) with: {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'uniform'}
0.953042 (0.004429) with: {'metric': 'manhattan', 'n_neighbors': 3, 'weights': 'distance'}
0.929356 (0.043943) with: {'metric': 'minkowski', 'n_neighbors': 2, 'weights': 'uniform'}
0.935084 (0.044697) with: {'metric': 'minkowski', 'n_neighbors': 2, 'weights': 'distance'}
0.952105 

In [173]:
best_p = -1
best_score = 0.0
best_k = -1
for method in ["uniform", "distance"]:
    for p in range(1, 6):
        knn_clf = KNeighborsClassifier(n_neighbors = 3, weights = method, p = p)
        knn_clf.fit(X_train, y_train)
        knn_score = knn_clf.score(X_test, y_test)
        if knn_score > best_score:
            best_score = knn_score
            best_p = p
            best_method = method


print("best_p = ", best_p)
print("best_method = ", best_method)
print("best_score = ", best_score) 

best_p =  2
best_method =  uniform
best_score =  0.779178674351585


In [175]:
#0.962426 (0.003822) with: {'metric': 'manhattan', 'n_neighbors': 2, 'weights': 'distance'}
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
  

# Split into training and test set
X_train, X_test, y_train, y_test = train_test_split(scaled_data, Y, 
                                                    test_size=0.3,random_state=42) # 70% training and 30% test

  
knn = KNeighborsClassifier(n_neighbors=3, weights='distance', algorithm='auto', leaf_size=30, p=2, metric='manhattan')
  
knn.fit(X_train, y_train)
  
# Predict on dataset which model has not seen before
print(knn.predict(X_test))

[1. 0. 0. ... 1. 0. 1.]


In [176]:
KNN_M=knn.predict(X).tolist()

In [177]:

multiple_case['KNN'] = KNN
multiple_case

Fuzzy Ratio  Cosine Similarity  Double Metaphone Score  \
0              100                1.0                     100   
1              100                1.0                     100   
2              100                1.0                     100   
3              100                1.0                     100   
4              100                1.0                     100   
...            ...                ...                     ...   
18501          100                1.0                     100   
18502          100                1.0                     100   
18503          100                1.0                     100   
18504          100                1.0                     100   
18505          100                1.0                     100   

       Jaro-Winkler Score  Levenshtein Distance Score  predict  KNN  
0                     1.0                           0      1.0    1  
1                     1.0                           0      1.0    1  
2                     1.0                           0      1.0    1  
3                     1.0                           0      1.0    1  
4                     1.0                           0      1.0    1  
...                   ...                         ...      ...  ...  
18501                 1.0                           0      2.0    1  
18502                 1.0                           0      2.0    1  
18503                 1.0                           0      2.0    1  
18504                 1.0                           0      2.0    1  
18505                 1.0                           0      2.0    1  

[18506 rows x 7 columns]

In [178]:
difference_knn=0

for i in range(len(multiple_case)):

    if multiple_case.at[i,'predict']!=multiple_case.at[i,'KNN']:
        difference_knn+=1
print(difference_knn)

6291
